# Generated by Django 4.0.3 on 2022-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=12345, max_length=254),
            preserve_default=False,
        ),
    ]
